spring:
  datasource:
    url: jdbc:h2:file:./target/database/h2_file
  jpa:
    properties:
      hibernate.format_sql: false
      hibernate.show_sql: false

hapi:
  fhir:
    version: r4
    server:
      path: /fhir/*
      name: Local HAPI FHIR Server with PS-CA Validation
      
    # Enable validation
    enable_repository_validating_interceptor: true
    
    # Validation configuration
    validation:
      requests_enabled: true
      responses_enabled: true
      
    # Implementation Guides configuration - using package names only
    implementationguides:
      # Canadian Baseline (required dependency for PS-CA)
       ca-baseline:
        name: hl7.fhir.ca.baseline
        version: 1.1.3
        url: https://packages.simplifier.net/hl7.fhir.ca.baseline/1.1.3    
      
      # PS-CA Implementation Guide  
      ps-ca:
        name: ca.infoway.io.psca
        version: 1.0.0-pre
        url: https://packages.simplifier.net/ca.infoway.io.psca/1.0.0-pre

# Logging configuration for debugging
logging:
  level:
    ca.uhn.fhir.validation: INFO
    ca.uhn.fhir.jpa.packages: INFO
    ca.uhn.fhir.jpa.validation: INFO